### ISSUE TITLE
babelrc in npm package

### ISSUE THREAD

**Issue by ikenfin** [stuartjnelson/badger-accordion#10]
Hello!

I'm using npm package, but it throws `TransformError` because of babel. Please, add `.babelrc` to `.npmignore`.

You can look at similar problems in other projects:
https://github.com/michaelcontento/redux-storage/issues/65
https://github.com/goatslacker/alt/issues/558

Thanks!

**Comment by stuartjnelson** [comment]
Hi @ikenfin,

Thanks for getting in touch! Thanks for bringing this to my attention. I'm afraid right now I'm pretty slammed so won't be able to investigate for at least 3 weeks. Feel free to submit a PR for this. Sorry i can't be more help now.

Thanks!
