### ISSUE TITLE
openAll(), closeAll() and headerIndex

### ISSUE THREAD

**Issue by plweil** [stuartjnelson/badger-accordion#14]
Unless I'm mistaken, I think there's a bug with the openAll() and closeAll() methods. 

Taking openAll() as an example:
 
      this.headers.forEach(function (header) {
       _this5.togglePanel('open', header);
      });

But togglePanel() is expecting the header **index** , rather than the object, as the second parameter.

This seems to work:

      this.headers.forEach(function (header, i) {
        _this5.togglePanel('open', i);
      });

**Comment by stuartjnelson** [comment]
Hey @plweil,

Thanks for raising this! This fell through somehow...

**Comment by stuartjnelson** [comment]
Hey @seanjhulse,

Thanks for being a legend and doing a PR. My apologies for not merging it sooner. I'm currently travelling so took some time off from developing. I'll leave this issue open as I agree it's been patched not fixed.

**Comment by stuartjnelson** [comment]
@plweil @seanjhulse,

Is either of you using the plugin on a project you'd be happy to share?  I'm wanting to get together a showcase of sites that are using the plugin it would be awesome to have your projects as part of it.

**Comment by seanjhulse** [comment]
Yes, we actually work together. We're attempting to consume your plugin as a part of a larger Wordpress plugin used at out university. As part of our obligations to the university, we aim to be as accessible as possible. @plweil is actually out of our office (bad timing!) but he is the head of accessibility in our department. 

We are going to try and use your Badger Accordion in our university's theme. @plweil is in the process of changing it and we both happened to discover the need for this PR! He found your accordion and found that it adhered closest to the accessibility guidelines. Although it may be somewhat premature to say so, we do plan on using your accordion in our university-wide Wordpress theme as part of a larger effort on campus to remain consistent and accessible! 

Please keep in touch. @plweil would be the best contact to let you know if and when it is officially integrated into the Wordpress theme. When that _likely does_ happen, your Badger Accordion will be a part of dozens (if not more) of websites using our Wordpress theme. He will probably be AFK for about 2 weeks, but after that he'll be back.

We really appreciate the work you've done in creating something accessible and elegant. I'll keep an eye out for more issues (feel free to create them yourself and PM/ref me). I'd be happy to continue contributing.

**Comment by stuartjnelson** [comment]
Wowow! That is super exciting for me! I actually emailed @plweil a few weeks ago (which I should have done a few months ago sorry!). Give me a shout if you run into any issues. 

It would be amazing to have some more help with the plugin.
