### ISSUE TITLE
Typo in the word

### ISSUE THREAD

**Issue by Eugeno** [stuartjnelson/badger-accordion#21]
initalised → initialized
In the options and class name

**Comment by stuartjnelson** [comment]
Hi @Eugeno,

Thanks for reporting the bug. I'm from the UK so we do spell it with an `s` (and I think I missed a letter, spellings not my thing). I do try and use USA spellings when developing and agree this should be changed. I've just updated the plugin and the docs. Thanks for your help!

Stuart
