### ISSUE TITLE
Nested accordions. 

### ISSUE THREAD

**Issue by justpie** [stuartjnelson/badger-accordion#22]
Hi,

Is it possible to do nested accordions?

I implemented the solution below but clicking on the nested accordion header closes the parent. 

Thanks!

```
   const elements = {
    accordions: document.querySelectorAll('.js-badger-accordion'),
  };

  Array.from(elements.accordions).forEach((accordion) => {
    //const badgerAccordion = new BadgerAccordion(`#${accordion.id}`);
    id = document.getElementById(accordion.id);
    const badgerAccordion = new BadgerAccordion(id);
  });
```

**Comment by stuartjnelson** [comment]
Hi @justpie,

I looked into this and implemented a fix for the plugin so it's now possible to create a nested accordion.  For a little more info how it will work checkout the [docs](https://github.com/stuartjnelson/badger-accordion#create-a-nested-accordion)
