### ISSUE TITLE
hiddenClass not working in 1.2.0

### ISSUE THREAD

**Issue by evandiamond** [stuartjnelson/badger-accordion#24]
# Prerequisites

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed
- [X] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

`hiddenClass` not working properly in 1.2.0
Should allow me to change class, but nothing changes. Surprisingly, `hidenClass` still works even though it's deprecated.

# Current Behavior
Unchanged selectors.

What is the current behavior?
Nothing changes and options not working properly.

## Steps to Reproduce

**Step 1:**
I changed my JS file to read:
```
hidenClass: 'is-hidden'
```
Hidden class becomes .is-hidden - which is good.

**Step 2:**
I changed my JS file to read:
```
hiddenClass: 'is-hidden'
```
Hidden class reverts to default `-ba-is-hidden` - which is bad.

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: MacOS
* Browser/s & version/s: Chrome Version 71.0.3578.98
* NPM version: 6.4.0
* Node version: v10.8.0

**Comment by stuartjnelson** [comment]
Hi @ evandiamond,

Thanks for raising such a detailed ticket. I have made a fix to this now in version `1.2.1` so you can now update the hidden class using the setting `hiddenClass: 'your-hidden-class'`. 

I'll close this issue but let me know if you have any more issues with this bug.

Thanks,
Stuart

**Comment by evandiamond** [comment]
Perfect and thank you so much! Really appreciate the fast response.

**Comment by stuartjnelson** [comment]
Awesome, glad I could fix it. Was a dumb mistake and a typo...

**Comment by stuartjnelson** [comment]
Oh and if you use the accordion on any project you'd be happy sharing I'd love be to see it! I'd like to get together a "Badger Accordion Hall Of Fame"

**Comment by marcobiedermann** [comment]
@stuartjnelson 

I think the typo still exists: https://github.com/stuartjnelson/badger-accordion/blob/master/src/js/badger-accordion.js#L33
