### ISSUE TITLE
Hello, When I click to the button the navigator try to open another page. I you help me please ?

### ISSUE THREAD

**Issue by BasseND** [stuartjnelson/badger-accordion#29]
# Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Please describe the behavior you are expecting

# Current Behavior

What is the current behavior?

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System:
* Browser/s & version/s:
* NPM version:
* Node version:

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by stuartjnelson** [comment]
Bonjour @BasseND,

Please could you give me some more information by filling out the issue template. Ideally if you could create an online example for me using something like https://codesandbox.io/ then I can help you debug.

By `navigator try to open` is this a link then when clicked on is opening a new window? Maybe preventing for the link would work - [w3schools example](https://www.w3schools.com/jsref/event_preventdefault.asp)

**Comment by stuartjnelson** [comment]
Hi @BasseND,

Since I haven't heard from you in over a month I'm going to close this issue. If you'd like some help please feel free to comment on here.
