### ISSUE TITLE
Typo on module package

### ISSUE THREAD

**Issue by mike3run** [stuartjnelson/badger-accordion#3]
Missing one `/`

https://github.com/stuartjnelson/badger-accordion/blob/94cde87781bbc86b1e36f45e7b3c86c2cb88f8a5/package.json#L6

**Comment by stuartjnelson** [comment]
Hi @mike3run,

Thanks for pointing this out. I've just corrected this now and will deploy this today

**Comment by stuartjnelson** [comment]
I've just deployed the fix for this. I'm closing the ticket. If you have any other issues with this @mike3run please let me know.
