### ISSUE TITLE
Extra code in the ESM version

### ISSUE THREAD

**Issue by mike3run** [stuartjnelson/badger-accordion#5]
https://github.com/stuartjnelson/badger-accordion/blob/94cde87781bbc86b1e36f45e7b3c86c2cb88f8a5/dist/badger-accordion.esm.js#L710-L719

:((((((((((((((((

**Comment by mike3run** [comment]
It seems like that's the code from your codepen demo and not strictly the code needed for a module 🤔

**Comment by stuartjnelson** [comment]
Hi @mike3run,

You are correct. I will sort this out now. Thanks for pointing out.

**Comment by stuartjnelson** [comment]
I've just deployed the fix for this. I'm closing the ticket. If you have any other issues with this @mike3run please let me know.
