### ISSUE TITLE
Use BEM modifiers to allow the styling of header

### ISSUE THREAD

**Issue by alanpilloud** [stuartjnelson/badger-accordion#9]
Hello,

Thanks a lot for this great accordion, very easy to implement.
Here is a suggestion : could we add a BEM modifier on both header and panel ?

For instance, this would allow us to style the active header with
```
.badger-accordion__header--open {
  // ...
}

.badger-accordion__panel--open {
  // ...
}
```

I have seen that the class `-ba-is-hidden` is applied on the panel and can be set through options, but that would be nice to use the same behaviour here too.

What do you think about it ?

**Comment by stuartjnelson** [comment]
Hi @alanpilloud!

Thanks for getting in touch and your kind words! I think its a great idea. Right now it's a pain to style with some funky sibling selectors...To be in keeping with the hidden class I think I will add the following class to both the panel and header. This will be a configurable class which by default is the same for both the header & panel.

```
.-ba-is-open {}
```

I'm going to run a new update this week and will include this in the update. Do you think it would also be helpful on the containing element to have an open class?


Let me know what you think. Thanks again for getting in touch with your idea!

**Comment by alanpilloud** [comment]
Hi @stuartjnelson 

This seems like a good compromise, great !

I'm trying to think of the different uses cases, but I don't think that the containing elements needs to get a class assigned.

Have a nice day

**Comment by stuartjnelson** [comment]
Hi @alanpilloud,

I have now implemented this in the latest release. Apologies for not getting it done sooner! Thanks again for your help improving the plugin.  I'm wanting to get together a showcase of sites that are using the plugin; do you have a public project that uses the plugin that you'd be happy to share?

**Comment by alanpilloud** [comment]
Thanks a lot for your work.

My teammate went with a custom made solution for the project that needed accordions. I'll test it again in a next project.

Have a nice day
